packages:
  # 应用
  - 'apps/*'
  # 公共包
  - 'packages/*'
  - 'packages/configs/*'
  # 工程化脚本
  - 'scripts'
catalog:
  '@swc/cli': ^0.7.9
  '@swc/core': ^1.15.8
  '@swc/jest': ^0.2.39
  swc-loader: ^0.2.6
  thread-loader: ^4.0.4

catalogs:
  # 工程化相关依赖
  cli:
    glob: ^13.0.0
    plop: ^4.0.4
    '@types/lodash-es': ^4.17.12
    lodash-es: ^4.17.21
    '@types/css': ^0.0.38
    css: ^3.0.0
    prettier-plugin-ejs: ^1.0.3
    ejs: ^3.1.10
    '@types/ejs': ^3.1.5
    '@rollup/plugin-alias': ^5.1.1
    '@rollup/plugin-commonjs': ^28.0.6
    '@rollup/plugin-node-resolve': ^16.0.1
    '@rollup/plugin-typescript': ^12.1.4
    rollup: ^4.44.2
    rollup-plugin-delete: ^3.0.1
    rollup-plugin-dts: ^6.2.1
    lint-staged: ^16.1.2
    cz-customizable: ^7.4.0
    commitizen: ^4.3.1
    '@commitlint/config-conventional': ^19.8.1
    '@commitlint/cli': ^19.8.1
    prettier: ^3.5.3
    husky: ^9.1.7
    '@unocss/eslint-plugin': ^66.1.4
    'eslint': ^9.22.0
    'eslint-plugin-format': ^1.0.1
    '@antfu/eslint-config': ^4.13.3
    turbo: ^2.5.4
    typescript: ~5.8.0
    '@types/node': ^22.14.0
    axios: ^1.10.0
    crypto-js: ^4.2.0
    jsencrypt: ^3.5.4
    '@types/crypto-js': ^4.2.2
    dayjs: ^1.11.13
    uuid: ^11.1.0
  # api生产依赖
  api_prod:
    # 核心
    '@nestjs/common': ^10.4.20
    rxjs: ^7.8.1
    reflect-metadata: ^0.2.2
    '@nestjs/core': ^10.4.20
    '@nestjs/mapped-types': ^2.1.0
    '@nestjs/event-emitter': ^3.0.1
    '@nestjs/platform-express': ^10.4.20
    '@nestjs/cqrs': ^11.0.3
    # 请求
    etag: ^1.8.1
    class-validator: ^0.14.1
    class-transformer: ^0.5.1
    nestjs-cls: ^6.0.1
    # 数据库
    '@nestjs/typeorm': ^10.0.2
    mysql2: ^3.14.1
    typeorm: 0.3.20
    '@nestjs/mongoose': ^10.1.0
    mongoose: ^8.18.0
    mongodb: 6.5.0
    # 配置
    joi: ^17.13.3
    '@nestjs/config': ^4.0.2
    cross-env: ^7.0.3
    # 日志
    nest-winston: ^1.10.2
    winston-daily-rotate-file: ^5.0.0
    winston: ^3.17.0
    chalk: ^5.6.0
    winston-mongodb: ^7.0.1
    # 缓存
    '@nestjs/cache-manager': ^3.1.0
    # 官方推荐@keyv/redis 但是底层用的是node-redis
    # 由于当前项目连接redis的底层库都是ioredis,所以用@keyv/valkey，底层是ioredis的分支
    '@keyv/valkey': ^1.0.11
    iovalkey: ^0.3.3
    cache-manager: ^7.2.8
    cacheable: ^2.3.2
    keyv: ^5.6.0
    ioredis: ^5.6.1
    # ioredis用到的异常库，
    redis-errors: ^1.2.0
    # 邮箱
    hbs: ^4.2.0
    nodemailer: ^7.0.3
    '@nestjs-modules/mailer': ^2.0.2
    # 安全
    csrf-csrf: ^4.0.3
    helmet: ^8.1.0
    '@nestjs/jwt': ^10.2.0
    cookie-parser: ^1.4.7
    '@nestjs/passport': ^11.0.5
    passport: ^0.7.0
    passport-custom: ^1.1.1
    '@nestjs/throttler': ^6.4.0
    '@nest-lab/throttler-storage-redis': ^1.1.0
    # 健康
    '@nestjs/terminus': ^10.3.0
    systeminformation: ^5.27.11
    # 定时任务
    '@nestjs/schedule': ^6.0.0
    # 验证码
    'svg-captcha': ^1.4.0
    # 第三方请求
    '@nestjs/axios': ^3.1.3
    # 队列
    '@nestjs/bullmq': ^11.0.2
    bullmq: ^5.54.0
    # 部署
    pm2: ^6.0.8
    # 文档
    '@scalar/nestjs-api-reference': ^1.0.7
    '@nestjs/swagger': ^8.1.1
  # api开发依赖
  api_dev:
    '@types/redis-errors': ^1.2.3
    '@types/multer': ^2.0.0
    '@types/cookie-parser': ^1.4.9
    '@types/passport-local': ^0.0.0
    copy-webpack-plugin: ^13.0.0
    webpack-bundle-analyzer: ^4.10.2
    '@types/hbs': ^4.0.5
    '@types/nodemailer': ^6.4.17
    run-script-webpack-plugin: ^0.2.3
    webpack: ^5.99.9
    webpack-node-externals: ^3.0.0
    nestjs-spelunker: ^1.3.2
    source-map-support: ^0.5.21
    supertest: ^7.0.0
    jest: ^29.7.0
    ts-jest: ^29.4.0
    ts-loader: ^9.5.2
    ts-node: ^10.9.2
    tsconfig-paths: ^4.2.0
    globals: ^16.0.0
    '@types/jest': ^29.5.14
    '@types/etag': ^1.8.4
    '@types/express': ^5.0.0
    '@types/supertest': ^6.0.2
    '@nestjs/cli': ^10.4.9
    '@nestjs/schematics': ^10.2.3
    '@nestjs/testing': ^10.4.20
  # web生产依赖
  web_prod:
    '@iconify/json': ^2.2.371
    '@iconify/vue': ^5.0.0
    chroma-js: ^3.1.2
    '@intlify/unplugin-vue-i18n': ^6.0.8
    vue-i18n: ^11.1.11
    '@vueuse/core': ^13.5.0
    element-plus: ^2.9.11
    nprogress: ^0.2.0
    vue: ^3.5.13
    vue-router: ^4.5.0
    pinia: ^3.0.1
    '@unocss/reset': ^66.1.4
  # web开发依赖
  web_dev:
    # 接口文件生成
    '@apidevtools/swagger-parser': ^12.1.0
    openapi-types: ^12.1.3
    # css工程化
    '@unocss/preset-icons': ^66.3.3
    unocss: ^66.1.4
    autoprefixer: ^10.4.21
    postcss: ^8.5.4
    '@unocss/preset-attributify': ^66.1.4
    # vite插件
    vite-plugin-compression: ^0.5.1
    vite-plugin-imagemin: ^0.6.1
    vite-plugin-html: ^3.2.2
    rollup-plugin-visualizer: ^6.0.3
    '@tsconfig/node22': ^22.0.1
    '@vitejs/plugin-vue': ^5.2.3
    '@vitejs/plugin-vue-jsx': ^4.1.2
    '@vue/tsconfig': ^0.7.0
    '@types/nprogress': ^0.2.3
    '@types/chroma-js': ^3.1.1
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.7.0
    vite: ^6.2.4
    vite-plugin-vue-devtools: ^7.7.2
    npm-run-all2: ^7.0.2
    vue-tsc: ^2.2.8
